import { Translations } from './types';

export const translations: Translations = {
  fr: {
    title: "IASMEEN",
    subtitle: "OSINT AI Studio",
    searchPlaceholder: {
      Email: "Entrez une adresse email...",
      "Nom de domaine": "Entrez un nom de domaine...",
      "Adresse IP": "Entrez une adresse IP...",
    },
    search: "Analyser",
    newSearch: "Nouvelle recherche",
    exportPDF: "Exporter en PDF",
    bedaTooltip: "BEDA permet d’extraire les métadonnées techniques (EXIF) d’une photo : localisation, appareil, date de prise, etc.",
    nayTooltip: "NAY explore les données réseau liées à une cible : ports ouverts, certificats SSL, techno utilisées, hébergeur, DNS, etc.",
    firaTooltip: "FIRA analyse la fiabilité et les incohérences des informations collectées pour donner un score de confiance.",
    resultsTitle: "Résultats de l'analyse",
    noResults: "Les résultats de l'analyse s'afficheront ici. Sélectionnez un type de cible pour commencer.",
    loading: "Analyse en cours...",
    error: "Une erreur est survenue. Veuillez réessayer.",
    footer: "© Yasmeen Nay – 2025. Tous droits réservés.",
    whois: {
        title: "Informations WHOIS",
        domainName: "Nom de domaine",
        registrar: "Registrar",
        creationDate: "Date de création",
        expiryDate: "Date d'expiration",
        updatedDate: "Dernière mise à jour",
        nameServers: "Serveurs de noms",
        registrantInfo: "Informations du titulaire",
        name: "Nom",
        organization: "Organisation",
    },
    nay: {
        title: "Analyse Réseau (NAY)",
        target: "Cible",
        location: "Localisation du serveur",
        hosting: "Hébergement",
        provider: "Fournisseur",
        asn: "ASN",
        openPorts: "Ports ouverts",
        port: "Port",
        service: "Service",
        sslCertificate: "Certificat SSL",
        issuer: "Émetteur",
        subject: "Sujet",
        validFrom: "Valide du",
        validTo: "Valide jusqu'au",
        noSsl: "Aucun certificat SSL détecté.",
        technologies: "Technologies détectées",
        dnsRecords: "Enregistrements DNS",
    },
    beda: {
        title: "Analyse EXIF (BEDA)",
        fileName: "Nom du fichier",
        fileSize: "Taille du fichier",
        imageProperties: "Propriétés de l'image",
        exifData: "Données EXIF",
        gpsData: "Données GPS",
        latitude: "Latitude",
        longitude: "Longitude",
        noGps: "Aucune donnée GPS trouvée.",
    },
    email: {
        title: "Analyse d'Email",
        emailAddress: "Adresse Email",
        syntaxValid: "Syntaxe valide",
        domain: "Domaine",
        mxRecordsFound: "Enregistrements MX trouvés",
        dataBreaches: "Fuites de données",
        noBreaches: "Aucune fuite de données connue trouvée.",
        source: "Source",
        date: "Date",
        socialProfiles: "Profils sociaux",
        noProfiles: "Aucun profil social trouvé.",
        platform: "Plateforme",
        yes: "Oui",
        no: "Non"
    },
    fira: {
        title: "Analyse de Fiabilité (FIRA)",
        runAnalysis: "Lancer l'analyse FIRA",
        loading: "Analyse FIRA en cours...",
        reliability: "Niveau de fiabilité",
        summary: "Résumé de l'analyse",
        findings: "Constatations",
        reliabilityLevels: {
            "Élevée": "Élevée",
            "Moyenne": "Moyenne",
            "Faible": "Faible",
            "High": "Élevée",
            "Medium": "Moyenne",
            "Low": "Faible",
        }
    }
  },
  en: {
    title: "IASMEEN",
    subtitle: "OSINT AI Studio",
    searchPlaceholder: {
      Email: "Enter an email address...",
      "Nom de domaine": "Enter a domain name...",
      "Adresse IP": "Enter an IP address...",
    },
    search: "Analyze",
    newSearch: "New Search",
    exportPDF: "Export to PDF",
    bedaTooltip: "BEDA extracts technical metadata (EXIF) from a photo: location, camera, date taken, etc.",
    nayTooltip: "NAY explores network data related to a target: open ports, SSL certificates, technologies used, host, DNS, etc.",
    firaTooltip: "FIRA analyzes the reliability and inconsistencies of the collected information to provide a trust score.",
    resultsTitle: "Analysis Results",
    noResults: "Analysis results will be displayed here. Select a target type to begin.",
    loading: "Analyzing...",
    error: "An error occurred. Please try again.",
    footer: "© Yasmeen Nay – 2025. All rights reserved.",
    whois: {
        title: "WHOIS Information",
        domainName: "Domain Name",
        registrar: "Registrar",
        creationDate: "Creation Date",
        expiryDate: "Expiry Date",
        updatedDate: "Last Updated",
        nameServers: "Name Servers",
        registrantInfo: "Registrant Information",
        name: "Name",
        organization: "Organization",
    },
    nay: {
        title: "Network Analysis (NAY)",
        target: "Target",
        location: "Server Location",
        hosting: "Hosting",
        provider: "Provider",
        asn: "ASN",
        openPorts: "Open Ports",
        port: "Port",
        service: "Service",
        sslCertificate: "SSL Certificate",
        issuer: "Issuer",
        subject: "Subject",
        validFrom: "Valid From",
        validTo: "Valid To",
        noSsl: "No SSL certificate detected.",
        technologies: "Detected Technologies",
        dnsRecords: "DNS Records",
    },
    beda: {
        title: "EXIF Analysis (BEDA)",
        fileName: "File Name",
        fileSize: "File Size",
        imageProperties: "Image Properties",
        exifData: "EXIF Data",
        gpsData: "GPS Data",
        latitude: "Latitude",
        longitude: "Longitude",
        noGps: "No GPS data found.",
    },
    email: {
        title: "Email Analysis",
        emailAddress: "Email Address",
        syntaxValid: "Valid Syntax",
        domain: "Domain",
        mxRecordsFound: "MX Records Found",
        dataBreaches: "Data Breaches",
        noBreaches: "No known data breaches found.",
        source: "Source",
        date: "Date",
        socialProfiles: "Social Profiles",
        noProfiles: "No social profiles found.",
        platform: "Platform",
        yes: "Yes",
        no: "No"
    },
    fira: {
        title: "Reliability Analysis (FIRA)",
        runAnalysis: "Run FIRA Analysis",
        loading: "FIRA analysis in progress...",
        reliability: "Reliability Level",
        summary: "Analysis Summary",
        findings: "Findings",
        reliabilityLevels: {
            "High": "High",
            "Medium": "Medium",
            "Low": "Low",
            "Élevée": "High",
            "Moyenne": "Medium",
            "Faible": "Low",
        }
    }
  },
};